version: '3'
services:
  app:
    image: sophialj/awe-frontend:latest
    restart: always
    ports:
      - "8889:8080"
      - "5555:22"
    command: "/usr/sbin/sshd -D"
    volumes:
      - ./app:/app
